dist: xenial
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- make install
- make test-install
- pip install codecov
script:
- make test
- ". venv/bin/activate; coverage run test/__init__.py"
- ". venv/bin/activate; flake8 --statistics --count"
after_success:
- codecov
deploy:
  provider: pypi
  user: __token__
  password: "$PYPI_TOKEN"
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    branch: main
    condition: "$TRAVIS_TEST_RESULT = 0"
    tags: true
    python: '3.6'
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: jdCNaDBFGJTicPHjoCzfGifivx0O5qO32wRTJKfi6UAFFADa58txxQCG1Zj762neJUb7G7mZXmWVtg11y9oInxrRQkqpTi5zCNAFSBbkMVRPnl/f9oRS2R50XCMj+ONxy52de9315WPUSDPmU+qDtWdwz5UCiOQKmyl8FcXDw68=
